In [ ]:
import pandas as pd
import numpy as np

np.random.seed(42)

dates = pd.date_range("2024-01-01", periods=180, freq="D")

data = pd.DataFrame({
    "date": dates,
    "oil_bbl": np.random.normal(1000, 80, len(dates)).cumsum(),
    "water_cut": np.random.uniform(0.1, 0.4, len(dates)),
    "pressure": np.random.normal(2500, 50, len(dates))
})

data.head()

In [11]:
from src.data_generator import generate_production_data

data = generate_production_data()
data.head()

        date      oil_bbl  water_cut     pressure
0 2024-01-01  1039.737132   0.158573  2459.088966
1 2024-01-02  2028.675988   0.316736  2604.619364
2 2024-01-03  3080.491071   0.184232  2449.699131
3 2024-01-04  4202.333460   0.107295  2439.290569
4 2024-01-05  5183.601190   0.293642  2557.905544

In [6]:
import sys
from pathlib import Path
import os

%load_ext autoreload
%autoreload 2

print(os.getcwd())
project_root = Path.cwd().parent 
sys.path.append(str(project_root)) #this works because it is running from notebooks and the root is the pareent directory of the notebooks folder

print(os.getcwd())
print(project_root)

from src.data_generator import generate_production_data

data = generate_production_data()
data.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/roger/projects/data-science-lab/notebooks
/home/roger/projects/data-science-lab/notebooks
/home/roger/projects/data-science-lab

        date      oil_bbl  water_cut     pressure
0 2024-01-01  1039.737132   0.158573  2459.088966
1 2024-01-02  2028.675988   0.316736  2604.619364
2 2024-01-03  3080.491071   0.184232  2449.699131
3 2024-01-04  4202.333460   0.107295  2439.290569
4 2024-01-05  5183.601190   0.293642  2557.905544